// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"go-bank-express/internal/delivery/handler"
	"go-bank-express/internal/delivery/http"
)

// Injectors from wire.go:

func Initialize() (Application, error) {
	pingHandler := handler.NewPing()
	userHandler := handler.NewUser()
	walletHandler := handler.NewWallet()
	transactionHandler := handler.NewTransaction()
	httpServer := http.NewHttpServer(pingHandler, userHandler, walletHandler, transactionHandler)
	application := newApplication(httpServer)
	return application, nil
}
